import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { isoNow, pathExists, readJson } from "./core.js";

const HOSTS = new Set(["codex", "claude", "cursor", "all"]);
const READ_TOOLS = ["ticket_get", "docs_search", "logs_search", "traces_search", "db_query_readonly", "deployments_list"];

function tomlString(value) {
  return JSON.stringify(String(value).replaceAll("\\", "/"));
}

function mcpEntries(registry) {
  if (!registry) return [];
  const capabilities = registry.environments?.production?.capabilities ?? {};
  return Object.entries(capabilities)
    .filter(([, source]) => source.status === "ready-for-host-rendering" && source.endpoint)
    .map(([capability, source]) => ({ name: `rooty_${capability}`, capability, ...source }));
}

function renderCodex(packageRoot, entries, demo) {
  const lines = [
    "# Generated by Rooty. Credential values must remain outside this file.",
    "sandbox_mode = \"read-only\"",
    "approval_policy = \"untrusted\"",
    ""
  ];
  if (demo) {
    lines.push(
      "[mcp_servers.rooty_demo]",
      "command = \"node\"",
      `args = [${tomlString(path.join(packageRoot, "src/mock-mcp-server.js"))}]`,
      `enabled_tools = [${READ_TOOLS.map(tomlString).join(", ")}]`,
      "required = true",
      ""
    );
  }
  for (const entry of entries) {
    lines.push(
      `[mcp_servers.${entry.name}]`,
      `url = ${tomlString(entry.endpoint)}`,
      ...(entry.auth === "oauth" ? ["auth = \"oauth\""] : []),
      ...(entry.auth === "bearer-env" ? [`bearer_token_env_var = ${tomlString(entry.bearer_token_env_var)}`] : []),
      ...(entry.auth === "oauth" && entry.oauth_access_token_env_var ? [`bearer_token_env_var = ${tomlString(entry.oauth_access_token_env_var)}`] : []),
      `enabled_tools = [${entry.allowed_tools.map(tomlString).join(", ")}]`,
      "enabled = true",
      "required = true",
      ""
    );
  }
  return `${lines.join("\n")}\n`;
}

function renderJsonHosts(packageRoot, entries, demo) {
  const servers = {};
  if (demo) {
    servers.rooty_demo = {
      type: "stdio",
      command: "node",
      args: [path.join(packageRoot, "src/mock-mcp-server.js")],
      env: { ROOTY_MCP_MODE: "snapshot-read-only" }
    };
  }
  for (const entry of entries) {
    const tokenEnv = entry.auth === "bearer-env" ? entry.bearer_token_env_var : entry.oauth_access_token_env_var;
    servers[entry.name] = {
      type: "http",
      url: entry.endpoint,
      ...(tokenEnv ? { headers: { Authorization: `Bearer \${${tokenEnv}}` } } : {})
    };
  }
  return { mcpServers: servers };
}

async function writeNew(filePath, content, files) {
  if (await pathExists(filePath)) throw new Error(`Refusing to overwrite existing host file: ${filePath}`);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");
  files.push(filePath);
}

export async function initializeHosts({ packageRoot, projectRoot, host, demo = false, activateConnectors = false }) {
  if (!HOSTS.has(host)) throw new Error(`Unsupported host: ${host}`);
  const requested = host === "all" ? ["codex", "claude", "cursor"] : [host];
  const files = [];
  const sourcesFile = path.join(projectRoot, ".investigator/sources.json");
  const registry = await pathExists(sourcesFile) ? await readJson(sourcesFile) : undefined;
  const availableEntries = mcpEntries(registry);
  const entries = activateConnectors ? availableEntries : [];
  const canonicalSkill = path.join(projectRoot, ".agents/skills/root-cause-investigator");
  const intendedTargets = [canonicalSkill];
  if (requested.includes("codex")) intendedTargets.push(path.join(projectRoot, ".codex/config.toml"));
  if (requested.includes("claude")) intendedTargets.push(path.join(projectRoot, ".claude/skills/root-cause-investigator"), path.join(projectRoot, ".mcp.json"), path.join(projectRoot, ".claude/settings.json"), path.join(projectRoot, ".claude/hooks/rooty-readonly.mjs"), path.join(projectRoot, ".claude/rooty-allowed-tools.json"));
  if (requested.includes("cursor")) intendedTargets.push(path.join(projectRoot, ".cursor/mcp.json"), path.join(projectRoot, ".cursor/rules/root-cause-investigator.mdc"));
  if (activateConnectors) intendedTargets.push(path.join(projectRoot, ".investigator/activated-connectors.json"));
  const conflicts = [];
  for (const target of intendedTargets) if (await pathExists(target)) conflicts.push(target);
  if (conflicts.length > 0) throw new Error(`Refusing to overwrite existing host paths: ${conflicts.join(", ")}`);
  await mkdir(path.dirname(canonicalSkill), { recursive: true });
  await cp(path.join(packageRoot, "skill/root-cause-investigator"), canonicalSkill, { recursive: true, errorOnExist: true, force: false });
  files.push(canonicalSkill);

  if (requested.includes("codex")) {
    await writeNew(path.join(projectRoot, ".codex/config.toml"), renderCodex(packageRoot, entries, demo), files);
  }
  if (requested.includes("claude")) {
    const claudeSkill = path.join(projectRoot, ".claude/skills/root-cause-investigator");
    await mkdir(path.dirname(claudeSkill), { recursive: true });
    await cp(path.join(packageRoot, "skill/root-cause-investigator"), claudeSkill, { recursive: true, errorOnExist: true, force: false });
    files.push(claudeSkill);
    await writeNew(path.join(projectRoot, ".mcp.json"), `${JSON.stringify(renderJsonHosts(packageRoot, entries, demo), null, 2)}\n`, files);
    const settings = {
      permissions: {
        deny: ["Edit", "Write", "NotebookEdit", "Bash"]
      },
      hooks: {
        PreToolUse: [{ matcher: "*", hooks: [{ type: "command", command: "node \"${CLAUDE_PROJECT_DIR}/.claude/hooks/rooty-readonly.mjs\"" }] }]
      }
    };
    await writeNew(path.join(projectRoot, ".claude/settings.json"), `${JSON.stringify(settings, null, 2)}\n`, files);
    const allowed = ["Read", "Glob", "Grep", "AskUserQuestion"];
    if (demo) for (const tool of READ_TOOLS) allowed.push(`mcp__rooty_demo__${tool}`);
    for (const entry of entries) for (const tool of entry.allowed_tools) allowed.push(`mcp__${entry.name}__${tool}`);
    await writeNew(path.join(projectRoot, ".claude/rooty-allowed-tools.json"), `${JSON.stringify({ allowedTools: allowed }, null, 2)}\n`, files);
    const hook = await readFile(path.join(packageRoot, "hosts/claude/rooty-readonly.mjs"), "utf8");
    await writeNew(path.join(projectRoot, ".claude/hooks/rooty-readonly.mjs"), hook, files);
  }
  if (requested.includes("cursor")) {
    await writeNew(path.join(projectRoot, ".cursor/mcp.json"), `${JSON.stringify(renderJsonHosts(packageRoot, entries, demo), null, 2)}\n`, files);
    const rule = await readFile(path.join(packageRoot, "hosts/cursor/root-cause-investigator.mdc"), "utf8");
    await writeNew(path.join(projectRoot, ".cursor/rules/root-cause-investigator.mdc"), rule, files);
  }
  if (activateConnectors) {
    const activation = {
      schema_version: 1,
      activated_at: isoNow(),
      connectors: entries.map((entry) => ({
        name: entry.name,
        capability: entry.capability,
        provider: entry.provider,
        endpoint: entry.endpoint,
        auth: entry.auth,
        ...(entry.bearer_token_env_var ? { bearer_token_env_var: entry.bearer_token_env_var } : {}),
        ...(entry.oauth_access_token_env_var ? { oauth_access_token_env_var: entry.oauth_access_token_env_var } : {}),
        allowed_tools: entry.allowed_tools,
        doctor_probe: entry.doctor_probe
      }))
    };
    await writeNew(path.join(projectRoot, ".investigator/activated-connectors.json"), `${JSON.stringify(activation, null, 2)}\n`, files);
  }
  return { files, connectorsActivated: entries.map((entry) => entry.name) };
}
