/* Rooty explainer stage.
 *
 * The renderer is a pure function of frame index. There are no CSS transitions
 * or animations anywhere: every opacity, offset, width and substring is
 * computed from `frame / fps`. That makes `seek(n)` reproducible, so the frame
 * grabber can run as slowly as it likes and still get identical output.
 *
 * Timeline schema (generated by tools/video/storyboard.mjs):
 *   { fps, width, height, scenes: [ Scene ] }
 *   Scene  = { id, act, kicker, title, sub, caption, durationMs, layout, panels }
 *   Panel  = { type, label, at, stagger, ...typeSpecificFields }
 * Items inside a panel may set an explicit `at` (ms from scene start); when
 * omitted the stage staggers them from the panel's own `at`.
 */

const XFADE_MS = 320;
const RISE_MS = 420;
const RISE_PX = 18;

const clamp01 = (value) => (value < 0 ? 0 : value > 1 ? 1 : value);
const easeOut = (t) => 1 - Math.pow(1 - clamp01(t), 3);
const easeInOut = (t) => (clamp01(t) < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2);

function ramp(localMs, at, durationMs) {
  if (durationMs <= 0) return localMs >= at ? 1 : 0;
  return clamp01((localMs - at) / durationMs);
}

function element(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

/** Collects the animators a scene needs so `seek` can replay them per frame. */
class Track {
  constructor() {
    this.animators = [];
  }

  rise(el, at, durationMs = RISE_MS) {
    this.animators.push({ kind: "rise", el, at, durationMs });
    return el;
  }

  fade(el, at, durationMs = RISE_MS) {
    this.animators.push({ kind: "fade", el, at, durationMs });
    return el;
  }

  type(el, text, at, durationMs) {
    this.animators.push({ kind: "type", el, text, at, durationMs });
    return el;
  }

  grow(el, at, durationMs, target) {
    this.animators.push({ kind: "grow", el, at, durationMs, target });
    return el;
  }

  states(el, states) {
    this.animators.push({ kind: "states", el, states: [...states].sort((a, b) => a.at - b.at) });
    return el;
  }

  caret(el, at, durationMs) {
    this.animators.push({ kind: "caret", el, at, durationMs });
    return el;
  }

  apply(localMs) {
    for (const animator of this.animators) {
      const { kind, el } = animator;
      if (kind === "rise") {
        const p = easeOut(ramp(localMs, animator.at, animator.durationMs));
        el.style.opacity = String(p);
        el.style.transform = `translateY(${((1 - p) * RISE_PX).toFixed(2)}px)`;
      } else if (kind === "fade") {
        el.style.opacity = String(easeOut(ramp(localMs, animator.at, animator.durationMs)));
      } else if (kind === "type") {
        const p = ramp(localMs, animator.at, animator.durationMs);
        const count = Math.round(p * animator.text.length);
        el.textContent = animator.text.slice(0, count);
      } else if (kind === "grow") {
        const p = easeInOut(ramp(localMs, animator.at, animator.durationMs));
        el.style.width = `${(p * animator.target).toFixed(2)}%`;
      } else if (kind === "caret") {
        // Deterministic 500ms blink once typing has finished.
        const typed = localMs >= animator.at + animator.durationMs;
        const blinkOn = Math.floor(Math.max(0, localMs) / 500) % 2 === 0;
        const visible = localMs >= animator.at && (!typed || blinkOn);
        el.style.opacity = visible ? "1" : "0";
      } else if (kind === "states") {
        let value = animator.states[0]?.value ?? "";
        for (const state of animator.states) {
          if (localMs >= state.at) value = state.value;
        }
        if (animator.states[0] && localMs < animator.states[0].at) value = animator.states[0].from ?? value;
        el.dataset.state = value;
      }
    }
  }
}

/* ------------------------------------------------------------------ panels */

function itemTime(panel, item, index) {
  if (typeof item.at === "number") return item.at;
  const base = panel.at ?? 0;
  const stagger = panel.stagger ?? 150;
  return base + index * stagger;
}

const PANELS = {
  terminal(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    if (panel.path !== undefined) {
      const bar = element("div", "term__bar");
      for (let index = 0; index < 3; index += 1) bar.append(element("span", "term__dot"));
      bar.append(element("span", "term__path", panel.path));
      root.append(track.fade(bar, panel.at ?? 0, 240));
    }
    const body = element("div", "term__body");
    root.append(body);

    let cursor = panel.at ?? 0;
    if (panel.command) {
      const line = element("div", "term__cmd");
      const text = element("span");
      const caret = element("span", "term__caret");
      line.append(text, caret);
      const at = panel.command.at ?? cursor;
      const duration = panel.command.durationMs ?? Math.max(500, panel.command.text.length * 32);
      track.fade(line, at, 160);
      track.type(text, panel.command.text, at, duration);
      track.caret(caret, at, duration);
      body.append(line);
      cursor = at + duration + (panel.command.settleMs ?? 320);
    }

    (panel.lines ?? []).forEach((item, index) => {
      const line = element("div", "term__line");
      line.dataset.tone = item.tone ?? "default";
      if (item.tag) {
        const tag = element("span", "term__tag", item.tag.text);
        tag.dataset.tone = item.tag.tone ?? "text";
        line.append(tag, document.createTextNode(item.text ?? ""));
      } else {
        line.textContent = item.text ?? "";
      }
      const at = typeof item.at === "number" ? item.at : cursor + index * (panel.stagger ?? 120);
      track.rise(line, at, 260);
      body.append(line);
    });
    return root;
  },

  tree(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const tree = element("div", "tree");
    (panel.items ?? []).forEach((item, index) => {
      const row = element("div", "tree__row");
      const indent = "  ".repeat(item.depth ?? 0);
      const name = element("span", "tree__name", `${indent}${item.name}`);
      name.dataset.kind = item.kind ?? "file";
      row.append(name);
      if (item.badge) row.append(element("span", "tree__badge", item.badge));
      track.rise(row, itemTime(panel, item, index), 240);
      tree.append(row);
    });
    root.append(tree);
    return root;
  },

  cards(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const list = element("div", "cards");
    (panel.items ?? []).forEach((item, index) => {
      const card = element("div", "card");
      card.dataset.state = item.state ?? "pending";
      const top = element("div", "card__top");
      if (item.id) top.append(element("span", "card__id", item.id));
      const title = element("span", "card__title", item.title ?? "");
      if (item.strikeAt !== undefined) {
        const strike = element("span", "card__strike");
        title.append(strike);
        track.grow(strike, item.strikeAt, 380, 100);
      }
      top.append(title);
      if (item.tag) {
        const tag = element("span", "card__tag", item.tag.text);
        tag.dataset.tone = item.tag.tone ?? "muted";
        top.append(tag);
      }
      card.append(top);
      if (item.body) card.append(element("div", "card__body", item.body));
      if (item.states) track.states(card, item.states);
      track.rise(card, itemTime(panel, item, index), 320);
      list.append(card);
    });
    root.append(list);
    return root;
  },

  steps(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const list = element("div", "steps");
    (panel.items ?? []).forEach((item, index) => {
      const step = element("div", "step");
      step.dataset.state = item.state ?? "pending";
      const rail = element("div", "step__rail");
      rail.append(element("span", "step__line"), element("span", "step__dot"));
      const text = element("div", "step__text");
      text.append(element("div", "step__label", item.label ?? ""));
      if (item.detail) text.append(element("div", "step__detail", item.detail));
      step.append(rail, text);
      if (item.states) track.states(step, item.states);
      track.rise(step, itemTime(panel, item, index), 260);
      list.append(step);
    });
    root.append(list);
    return root;
  },

  chat(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const list = element("div", "chat");
    (panel.items ?? []).forEach((item, index) => {
      const bubble = element("div", "bubble");
      bubble.dataset.role = item.role ?? "agent";
      if (item.who) bubble.append(element("span", "bubble__who", item.who));
      const at = itemTime(panel, item, index);
      if (item.typeMs) {
        const text = element("span");
        bubble.append(text);
        track.type(text, item.text ?? "", at, item.typeMs);
      } else {
        bubble.append(document.createTextNode(item.text ?? ""));
      }
      track.rise(bubble, at, 300);
      list.append(bubble);
    });
    root.append(list);
    return root;
  },

  chips(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const grid = element("div", "chips");
    if (panel.columns) grid.style.gridTemplateColumns = `repeat(${panel.columns}, minmax(0, 1fr))`;
    (panel.items ?? []).forEach((item, index) => {
      const chip = element("div", "chip");
      const head = element("div", "chip__head");
      head.append(element("span", "chip__name", item.name ?? ""));
      if (item.classification) {
        const badge = element("span", "chip__class", item.classification);
        badge.dataset.tone = item.classification.toLowerCase();
        head.append(badge);
      }
      chip.append(head);
      if (item.query) chip.append(element("div", "chip__query", item.query));
      if (item.text) chip.append(element("div", "chip__text", item.text));
      track.rise(chip, itemTime(panel, item, index), 300);
      grid.append(chip);
    });
    root.append(grid);
    return root;
  },

  timeline(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const list = element("div", "tl");
    (panel.items ?? []).forEach((item, index) => {
      const row = element("div", "tl__row");
      row.dataset.tone = item.tone ?? "default";
      row.append(element("div", "tl__time", item.time ?? ""));
      const rail = element("div", "tl__rail");
      rail.append(element("span", "tl__line"), element("span", "tl__dot"));
      row.append(rail);
      const text = element("div", "tl__text");
      if (item.flag) text.append(element("span", "tl__flag", item.flag), element("br"));
      text.append(document.createTextNode(item.text ?? ""));
      if (item.ref) text.append(element("span", "tl__ref", ` ${item.ref}`));
      row.append(text);
      track.rise(row, itemTime(panel, item, index), 280);
      list.append(row);
    });
    root.append(list);
    return root;
  },

  verdicts(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const grid = element("div", "verdicts");
    (panel.items ?? []).forEach((item, index) => {
      const verdict = element("div", "verdict");
      verdict.dataset.state = item.state ?? "dimmed";
      verdict.append(element("div", "verdict__label", item.label ?? ""));
      if (item.detail) verdict.append(element("div", "verdict__detail", item.detail));
      if (item.states) track.states(verdict, item.states);
      track.rise(verdict, itemTime(panel, item, index), 320);
      grid.append(verdict);
    });
    root.append(grid);
    return root;
  },

  chain(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const list = element("div", "chain");
    (panel.items ?? []).forEach((item, index) => {
      const row = element("div", "chain__row");
      row.append(element("div", "chain__seq", item.seq ?? ""));
      const block = element("div", "chain__block");
      block.append(element("span", "chain__id", item.id ?? ""));
      if (item.classification) {
        const badge = element("span", "chip__class", item.classification);
        badge.dataset.tone = item.classification.toLowerCase();
        block.append(badge);
      }
      block.append(element("span", "chain__hash", item.previous ?? ""));
      block.append(element("span", "chain__arrow", "\u2192"));
      block.append(element("span", "chain__hash", item.hash ?? ""));
      row.append(block);
      track.rise(row, itemTime(panel, item, index), 260);
      list.append(row);
    });
    root.append(list);
    return root;
  },

  report(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const body = element("div", "report");
    (panel.items ?? []).forEach((item, index) => {
      const line = element("div", "report__line", item.text ?? "");
      line.dataset.tone = item.tone ?? "default";
      track.rise(line, itemTime(panel, item, index), 220);
      body.append(line);
    });
    root.append(body);
    return root;
  },

  stats(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const grid = element("div", "stats");
    if (panel.columns) grid.style.gridTemplateColumns = `repeat(${panel.columns}, minmax(0, 1fr))`;
    (panel.items ?? []).forEach((item, index) => {
      const stat = element("div", "stat");
      stat.append(element("div", "stat__value", item.value ?? ""));
      stat.append(element("div", "stat__label", item.label ?? ""));
      track.rise(stat, itemTime(panel, item, index), 320);
      grid.append(stat);
    });
    root.append(grid);
    return root;
  },

  diff(panel, track) {
    const root = element("div", `panel ${panel.plain ? "panel--plain" : ""}`);
    if (panel.label) root.append(track.fade(element("div", "panel__label", panel.label), panel.at ?? 0, 240));
    const body = element("div", "diff");
    (panel.items ?? []).forEach((item, index) => {
      const line = element("div", "diff__line", item.text ?? "");
      line.dataset.tone = item.tone ?? "kept";
      track.rise(line, itemTime(panel, item, index), 220);
      body.append(line);
    });
    root.append(body);
    return root;
  },

  titleCard(panel, track) {
    const root = element("div", "panel panel--plain");
    const card = element("div", "title-card");
    if (panel.eyebrow) card.append(track.rise(element("div", "title-card__eyebrow", panel.eyebrow), panel.at ?? 0, 380));
    card.append(track.rise(element("h1", "title-card__title", panel.title ?? ""), (panel.at ?? 0) + 180, 460));
    card.append(track.grow(element("div", "title-card__rule"), (panel.at ?? 0) + 420, 620, panel.ruleWidth ?? 26));
    if (panel.sub) card.append(track.rise(element("p", "title-card__sub", panel.sub), (panel.at ?? 0) + 560, 460));
    if (panel.meta) card.append(track.rise(element("div", "title-card__meta", panel.meta), (panel.at ?? 0) + 820, 420));
    root.append(card);
    return root;
  }
};

/* ------------------------------------------------------------------- stage */

class Stage {
  constructor(timeline) {
    this.timeline = timeline;
    this.fps = timeline.fps;
    this.scenes = [];
    this.actEl = document.getElementById("chrome-act");
    this.progressEl = document.getElementById("progress-fill");
    this.container = document.getElementById("scenes");
    this.build();
  }

  build() {
    let start = 0;
    for (const scene of this.timeline.scenes) {
      const track = new Track();
      const root = element("section", "scene");
      root.dataset.id = scene.id;

      const head = element("div", "scene__head");
      if (scene.kicker) head.append(track.rise(element("div", "scene__kicker", scene.kicker), 0, 320));
      if (scene.title) head.append(track.rise(element("h2", "scene__title", scene.title), 60, 380));
      if (scene.sub) head.append(track.rise(element("p", "scene__sub", scene.sub), 140, 380));
      if (scene.kicker || scene.title || scene.sub) root.append(head);

      const body = element("div", "scene__body");
      body.dataset.layout = scene.layout ?? "single";
      for (const panel of scene.panels ?? []) {
        const builder = PANELS[panel.type];
        if (!builder) throw new Error(`Unknown panel type: ${panel.type}`);
        body.append(builder(panel, track));
      }
      root.append(body);

      if (scene.caption) {
        const caption = element("p", "scene__caption");
        caption.innerHTML = scene.caption.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
        root.append(track.rise(caption, scene.captionAt ?? 900, 380));
      }

      this.container.append(root);
      this.scenes.push({ ...scene, root, track, start, end: start + scene.durationMs });
      start += scene.durationMs;
    }
    this.durationMs = start;
    this.frameCount = Math.round((this.durationMs / 1000) * this.fps);
  }

  seek(frame) {
    const timeMs = (frame / this.fps) * 1000;
    let activeIndex = 0;
    for (let index = 0; index < this.scenes.length; index += 1) {
      if (timeMs >= this.scenes[index].start) activeIndex = index;
    }
    const active = this.scenes[activeIndex];
    const localMs = timeMs - active.start;
    const incoming = easeOut(ramp(localMs, 0, XFADE_MS));

    for (let index = 0; index < this.scenes.length; index += 1) {
      const scene = this.scenes[index];
      const isActive = index === activeIndex;
      const isOutgoing = index === activeIndex - 1 && incoming < 1;
      scene.root.dataset.visible = isActive || isOutgoing ? "1" : "0";
      if (isActive) {
        scene.root.style.opacity = String(incoming);
        scene.track.apply(localMs);
      } else if (isOutgoing) {
        scene.root.style.opacity = String(1 - incoming);
        scene.track.apply(scene.durationMs);
      }
    }

    this.actEl.textContent = active.act ?? "";
    this.progressEl.style.width = `${((timeMs / this.durationMs) * 100).toFixed(3)}%`;
  }
}

// The stage is authored at a fixed size. When the viewport matches exactly (the
// frame renderer overrides device metrics to do this) no transform is applied at
// all, so text lands on whole pixels. Any other viewport gets scaled to fit,
// which is only used when previewing in a normal browser window.
function fitViewport(stageEl, width, height) {
  const scale = Math.min(window.innerWidth / width, window.innerHeight / height);
  stageEl.style.transform = scale === 1 ? "none" : `scale(${scale})`;
}

async function boot() {
  const params = new URLSearchParams(window.location.search);
  const response = await fetch(params.get("timeline") ?? "timeline.json");
  const timeline = await response.json();
  const stageEl = document.getElementById("stage");
  stageEl.style.width = `${timeline.width}px`;
  stageEl.style.height = `${timeline.height}px`;
  fitViewport(stageEl, timeline.width, timeline.height);

  const stage = new Stage(timeline);
  window.rootyStage = stage;
  window.rootySeek = (frame) => stage.seek(frame);
  window.rootyFit = () => fitViewport(stageEl, timeline.width, timeline.height);
  window.addEventListener("resize", window.rootyFit);
  await document.fonts.ready;
  stage.seek(Number(params.get("frame") ?? 0));
  document.documentElement.dataset.ready = "1";
}

boot();
